# Generated by Django 2.2.1 on 2019-06-25 14:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Follow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FollowCond1', models.IntegerField()),
                ('FollowCond2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GalleryReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.IntegerField(blank=True, null=True)),
                ('Gallery', models.IntegerField(blank=True, null=True)),
                ('UpdateDateTime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gallery', models.IntegerField(blank=True, null=True)),
                ('Photo', models.ImageField(blank=True, default='photos/default.jpg', null=True, upload_to='')),
                ('UploadDateTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('Location', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('Description', models.CharField(blank=True, default='', max_length=1024, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoReaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User', models.IntegerField(blank=True, null=True)),
                ('Photo', models.IntegerField(blank=True, null=True)),
                ('UpdateDateTime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProfilePhoto', models.ImageField(blank=True, default='/profile_pics/default.jpg', null=True, upload_to='')),
                ('RegisterDateTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('BirthDate', models.DateField(blank=True, null=True)),
                ('Bio', models.CharField(blank=True, default='', max_length=500, null=True)),
                ('FirstName', models.CharField(blank=True, default='', max_length=20)),
                ('LastName', models.CharField(blank=True, default='', max_length=30)),
                ('Sex', models.CharField(choices=[('ML', 'ML'), ('FM', 'FM'), ('OC', 'OC'), ('NA', 'NA')], default='NA', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PhotoComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Photo', models.IntegerField(blank=True, null=True)),
                ('UpdateDateTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('Comment', models.CharField(blank=True, max_length=1024, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Gallery', models.IntegerField(blank=True, null=True)),
                ('UploadDateTime', models.DateTimeField(default=None, editable=False, null=True)),
                ('Comment', models.CharField(blank=True, max_length=1024, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('AlbumCover', models.ImageField(blank=True, default='album_cover/default.jpeg', null=True, upload_to='')),
                ('Name', models.CharField(max_length=50)),
                ('Description', models.CharField(blank=True, default='', max_length=1024, null=True)),
                ('UploadDateTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('GalleryOwner', models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
