# Generated by Django 2.2.1 on 2019-05-13 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='User',
            new_name='user',
        ),
    ]
