# Generated by Django 2.2.1 on 2019-05-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='follow',
            name='FollowCond1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='follow',
            name='FollowCond2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallerycomment',
            name='Gallery',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gallerycomment',
            name='User',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='galleryreaction',
            name='Gallery',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='galleryreaction',
            name='User',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photo',
            name='Gallery',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photocomment',
            name='Photo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photocomment',
            name='User',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photoreaction',
            name='Photo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photoreaction',
            name='User',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
