# Generated by Django 2.2.1 on 2019-05-13 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0002_auto_20190513_2014'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='user',
            new_name='User',
        ),
    ]
