# Generated by Django 2.2.1 on 2019-05-13 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0004_auto_20190513_2021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryreaction',
            name='ReactionType',
        ),
        migrations.RemoveField(
            model_name='photoreaction',
            name='ReactionType',
        ),
    ]
