# Generated by Django 2.2.1 on 2019-05-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0005_auto_20190513_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='StorageLoc',
        ),
        migrations.AddField(
            model_name='photo',
            name='ProfilePhoto',
            field=models.ImageField(blank=True, default='', null=True, upload_to='profile_pics/'),
        ),
    ]
