# Generated by Django 2.2.1 on 2019-05-14 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0006_auto_20190514_0030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='ProfilePhoto',
            new_name='Photo',
        ),
    ]
