# Generated by Django 2.2.1 on 2019-05-14 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0007_auto_20190514_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='Photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to=''),
        ),
    ]
