# Generated by Django 2.2.1 on 2019-05-14 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0008_auto_20190514_0138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='Photo',
            field=models.ImageField(blank=True, default='', null=True, upload_to='photos/'),
        ),
    ]
