# Generated by Django 2.2.1 on 2019-05-14 09:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webmain', '0011_auto_20190514_0936'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Friendship',
            new_name='Follow',
        ),
    ]
