# Generated by Django 2.2.1 on 2019-05-15 00:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0012_auto_20190514_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerycomment',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
