# Generated by Django 2.2.1 on 2019-05-15 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0013_auto_20190515_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photocomment',
            name='User',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
