# Generated by Django 2.2.1 on 2019-05-15 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0014_auto_20190515_0033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='Photo',
            field=models.FileField(blank=True, default='photos/default.jpg', null=True, upload_to='photos/'),
        ),
    ]
