# Generated by Django 2.2.1 on 2019-05-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0015_auto_20190515_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='PhotoUrl',
            field=models.URLField(blank=True),
        ),
    ]
