# Generated by Django 2.2.1 on 2019-05-16 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0016_photo_photourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='Photo',
            field=models.ImageField(blank=True, default='photos/default.jpg', null=True, upload_to='photos/'),
        ),
    ]
