# Generated by Django 2.2.1 on 2019-05-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0017_auto_20190516_0607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='Visibility',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='PhotoUrl',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='Visibility',
        ),
        migrations.AddField(
            model_name='gallery',
            name='AlbumCover',
            field=models.ImageField(default='album_cover/default.jpeg', upload_to='album_cover/'),
        ),
    ]
