# Generated by Django 2.2.1 on 2019-05-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0018_auto_20190516_0949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='FirstName',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='LastName',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Sex',
            field=models.CharField(blank=True, choices=[('ML', 'ML'), ('FM', 'FM'), ('OC', 'OC'), ('NA', 'NA')], default='NA', max_length=2),
        ),
    ]
