# Generated by Django 2.2.1 on 2019-05-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0019_auto_20190518_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Sex',
            field=models.CharField(blank=True, choices=[('ML', 'MALE'), ('FM', 'FEMALE'), ('OC', 'OTHER'), ('NA', 'NO ANSWER')], default='NA', max_length=10),
        ),
    ]
