# Generated by Django 2.2.1 on 2019-05-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0020_auto_20190518_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerycomment',
            name='Comment',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='photocomment',
            name='Comment',
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
