# Generated by Django 2.2.1 on 2019-05-16 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='PhotoUrl',
            field=models.URLField(blank=True),
        ),
    ]
