# Generated by Django 2.2.1 on 2019-05-18 17:36

from django.db import migrations, models
import webmain.storage


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0003_auto_20190518_1640'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('storage_1_ID', models.TextField()),
                ('storage_2_ID', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='Photo',
            field=models.ImageField(blank=True, default='photos/default.jpg', null=True, storage=webmain.storage.ExternalStorage(), upload_to='images/'),
        ),
    ]
