# Generated by Django 2.2.1 on 2019-05-18 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0004_auto_20190518_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='PhotoUrl',
        ),
    ]
