# Generated by Django 2.2.1 on 2019-05-18 18:47

from django.db import migrations, models
import webmain.storage


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0005_remove_photo_photourl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='AlbumCover',
            field=models.ImageField(default='album_cover/default.jpeg', storage=webmain.storage.ExternalStorage(), upload_to='album_cover/'),
        ),
    ]
