# Generated by Django 2.2.1 on 2019-05-20 20:47

from django.db import migrations, models
import webmain.storage


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0008_auto_20190519_1941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='AlbumCover',
            field=models.ImageField(default='album_cover/default.jpeg', storage=webmain.storage.ExternalStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='Photo',
            field=models.ImageField(default='photos/default.jpg', storage=webmain.storage.ExternalStorage(), upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='ProfilePhoto',
            field=models.ImageField(default='profile_pics/default.jpg', storage=webmain.storage.ExternalStorage(), upload_to='profile_pics/'),
        ),
    ]
