# Generated by Django 2.2.1 on 2019-05-20 21:47

from django.db import migrations, models
import django.db.models.deletion
import webmain.storage


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0009_auto_20190520_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='AlbumCover',
            field=models.ImageField(storage=webmain.storage.ExternalStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='photo',
            name='Gallery',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='webmain.Gallery'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='Photo',
            field=models.ImageField(storage=webmain.storage.ExternalStorage(), upload_to=''),
        ),
    ]
