# Generated by Django 2.2.1 on 2019-05-22 00:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0012_auto_20190522_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='GalleryOwner',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
