# Generated by Django 2.2.1 on 2019-06-23 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webmain', '0013_auto_20190522_0041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallerycomment',
            name='Gallery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webmain.Gallery'),
        ),
        migrations.AlterField(
            model_name='gallerycomment',
            name='User',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
