# Generated by Django 2.2.1 on 2019-05-08 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Galleries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=75)),
                ('Description', models.CharField(blank=True, default='', max_length=1000, null=True)),
                ('Visibility', models.CharField(blank=True, default='pu', max_length=2, null=True)),
                ('UploadDateTime', models.DateTimeField(auto_now_add=True, null=True)),
                ('GalleryOwner', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
