# Generated by Django 2.2.1 on 2019-05-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galleries',
            name='Description',
            field=models.CharField(blank=True, default='', max_length=1024, null=True),
        ),
    ]
