# Generated by Django 2.2.1 on 2019-05-16 14:39

from django.db import migrations, models
import webmain.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('storage_1_ID', models.TextField()),
                ('storage_2_ID', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('cover', models.ImageField(storage=webmain.storage.ExternalStorage(), upload_to='images/')),
            ],
        ),
    ]
