# Generated by Django 2.2.1 on 2019-05-14 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileentry',
            old_name='storage_1',
            new_name='storage_1_EXT_URL',
        ),
        migrations.RenameField(
            model_name='fileentry',
            old_name='storage_2',
            new_name='storage_1_hostname',
        ),
        migrations.AddField(
            model_name='fileentry',
            name='storage_2_EXT_URL',
            field=models.TextField(default='init'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileentry',
            name='storage_2_hostname',
            field=models.TextField(default='init'),
            preserve_default=False,
        ),
    ]
