# Generated by Django 2.2.1 on 2019-05-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FileEntry',
        ),
    ]
