# Generated by Django 2.2.1 on 2019-05-14 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190514_1920'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileentry',
            old_name='storage_1_EXT_URL',
            new_name='storage_1_ID',
        ),
        migrations.RenameField(
            model_name='fileentry',
            old_name='storage_1_hostname',
            new_name='storage_2_ID',
        ),
        migrations.RemoveField(
            model_name='fileentry',
            name='storage_2_EXT_URL',
        ),
        migrations.RemoveField(
            model_name='fileentry',
            name='storage_2_hostname',
        ),
    ]
